COUNTRY_CHOICES = [
    ('AD', 'Andorra'),
    ('AM', 'Armenia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaijan'),
    ('BY', 'Belarus'),
    ('BE', 'Belgium'),
    ('BA', 'Bosnia and Herzegovina'),
    ('BG', 'Bulgaria'),
    ('HR', 'Croatia'),
    ('CY', 'Cyprus'),
    ('CZ', 'Czech Republic'),
    ('DK', 'Denmark'),
    ('EE', 'Estonia'),
    ('FI', 'Finland'),
    ('FR', 'France'),
    ('GE', 'Georgia'),
    ('DE', 'Germany'),
    ('GR', 'Greece'),
    ('HU', 'Hungary'),
    ('IS', 'Iceland'),
    ('IE', 'Ireland'),
    ('IT', 'Italy'),
    ('KZ', 'Kazakhstan'),
    ('XK', 'Kosovo'),
    ('LV', 'Latvia'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('MK', 'North Macedonia'),
    ('MT', 'Malta'),
    ('MD', 'Moldova'),
    ('MC', 'Monaco'),
    ('ME', 'Montenegro'),
    ('NL', 'Netherlands'),
    ('NO', 'Norway'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('RO', 'Romania'),
    ('SM', 'San Marino'),
    ('RS', 'Serbia'),
    ('SK', 'Slovakia'),
    ('SI', 'Slovenia'),
    ('ES', 'Spain'),
    ('SE', 'Sweden'),
    ('CH', 'Switzerland'),
    ('TR', 'Turkey'),
    ('UA', 'Ukraine'),
    ('US', 'United States'),
    ('CA', 'Canada'),
]
